services:
  rstudio:
    build:
      context: .
      dockerfile: docker/rstudio/Dockerfile
    image: rtadb/rstudio
    container_name: rtadb-rstudio
    environment:
      TZ: Asia/Tokyo
      DISABLE_AUTH: true
    ports:
      - "8787:8787"
    volumes:
      - .:/home/rstudio/rtadb
  database:
    image: postgis/postgis
    container_name: rtadb_database
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: p@ssw0rd
      POSTGRES_DB: traffic_accident_database
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - data:/var/lib/postgresql/data
volumes:
  data:
